# Generated by Django 5.0.6 on 2024-06-18 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rewardCoin', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rewardsStatus', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold'), ('AVAILABLE', 'Available'), ('EXPIRED', 'Expired'), ('REDEEMED', 'Redeemed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
