# Generated by Django 5.0.6 on 2024-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_rewards_rewardsstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='rewardsStatus',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('COMPLETE', 'Complete'), ('IN_PROGRESS', 'In Progress'), ('AVAILABLE', 'Available'), ('ON_HOLD', 'On Hold'), ('EXPIRED', 'Expired'), ('REDEEMED', 'Redeemed'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=50),
        ),
    ]
